package tech.arnav.twofac.backup

import io.github.vinceglb.filekit.FileKit
import io.github.vinceglb.filekit.div
import io.github.vinceglb.filekit.name
import io.github.vinceglb.filekit.readBytes
import io.github.vinceglb.filekit.write
import io.github.vinceglb.filekit.dialogs.FileKitType
import io.github.vinceglb.filekit.dialogs.openDirectoryPicker
import io.github.vinceglb.filekit.dialogs.openFilePicker

internal actual suspend fun saveBackupFileWithPicker(
    suggestedFileName: String,
    content: ByteArray,
): Boolean {
    // Let the user choose the destination folder; cancel means no write.
    val directory = FileKit.openDirectoryPicker() ?: return false
    // Compose the final backup path inside the selected folder.
    val destination = directory / suggestedFileName
    // Persist the backup bytes exactly as generated by sharedLib.
    destination write content
    return true
}

internal actual suspend fun pickBackupFileWithPicker(): PickedBackupFile? {
    // Restrict selection to JSON files; cancel yields null.
    val file = FileKit.openFilePicker(
        type = FileKitType.File(listOf("json")),
    ) ?: return null

    // Keep the picked file name as an identifier and load full bytes for import.
    return PickedBackupFile(
        id = file.name,
        content = file.readBytes(),
    )
}
